### ISSUE TITLE
Error with `cache_slice` when generating.

### ISSUE THREAD

**Issue by homerjed** [AakashKumarNain/mistral_jax#1]
Hi Aakash, 

Thanks for this amazing code. I've followed the `instructions.md` (using your `requirements.txt` of course) and have found an error I haven't been able to fix myself, referring to the line

https://github.com/AakashKumarNain/mistral_jax/blob/42f6a947e7f5ccbddfa0f40c0a6a43f5796d8055/mistral_jax/one_file_ref.py#L121

```python

    @partial(jax.jit, static_argnums=(2, 3))
    # @eqx.filter_jit # Possible fix?
    def get_cache_slice(self, x, pos, kv_repeats):
        x_slice = x.at[:pos, :, :].get() # Original
        # x_slice = jax.lax.dynamic_slice(x, (0, 0, 0), (pos, x.shape[1] - 1, x.shape[2] - 1)) # Possible fix?
        x_slice = jnp.repeat(x_slice, kv_repeats, axis=1)
        return x_slice

```

when running `python -m one_file_ref.py`, which is where the error appears to be. I attempted a fix in a few different ways but this hasn't worked. 

The error is 

```
IndexError: Array slice indices must have static start/stop/step to be used with NumPy indexing syntax. Found slice(None, Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=2/0)>, None). To index a statically sized array at a dynamic position, try lax.dynamic_slice/dynamic_update_slice (JAX does not support dynamically sized arrays within JIT compiled functions).
```

I'm surprised as I'm using the correct version of `jax` so I'm not sure why this wouldn't work! 

Cheers

**Comment by AakashKumarNain** [comment]
`eqx.filter_jit` should work. Let me check this once

**Comment by AakashKumarNain** [comment]
@homerjed thanks for reporting the error. I figured out the problem. I think I updated this file while making other changes. 
This is the line that was problematic:
```python
vmapped_model = eqx.filter_vmap(
        eqx.filter_jit(model), in_axes=(0, None, None, None, None, 0, 0)
)
```

Why is this problematic?

In `one_file_ref.py`, we are jitting individual methods, so that we can carry out certain operations (e.g. `.item()`) when generating samples. Given that the methods have already been jitted indivdually, using `eqx._filter_jit(...)` to jit the whole `__call__` doesn't make sense.

Here is a sample run on my side:

<img width="943" alt="Screenshot 2024-07-01 at 9 43 49 PM" src="https://github.com/AakashKumarNain/mistral_jax/assets/11736571/60f002f6-f03a-4891-ba5e-3682ec7b180e">


Thanks for reporting it. Let me know if you run into any more issues
